{{- if .Values.persistence.enabled -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "fullname" . }}-suitecrm
  annotations:
    volume.alpha.kubernetes.io/storage-class: {{ .Values.persistence.suitecrm.storageClass | quote }}
spec:
  accessModes:
    - {{ .Values.persistence.suitecrm.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.suitecrm.size | quote }}
{{- end -}}
