name: suitecrm
version: 0.3.1
description: Web publishing platform for building blogs and websites.
keywords:
- suitecrm
- crm
- http
- web
- application
- php
home: https://www.suitecrm.com/
sources:
- https://github.com/bitnami/bitnami-docker-suitecrm
maintainers:
- name: Bitnami
  email: containers@bitnami.com
engine: gotpl
